<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hogwarts [

<!ELEMENT Hogwarts (Rooms, Teachers, Courses) >

<!ELEMENT Rooms (Room*) >
 <!ELEMENT Room EMPTY >
  <!ATTLIST Room
    name    ID    #REQUIRED
    nrSeats CDATA #IMPLIED >

<!ELEMENT Teachers (Teacher*) >
 <!ELEMENT Teacher (Title*) >
  <!ELEMENT Title (#PCDATA) >
  <!ATTLIST Teacher
    name ID    #REQUIRED
    room IDREF #REQUIRED >

<!ELEMENT Courses (Course*) >
 <!ELEMENT Course (Class*) >
  <!ATTLIST Course
    name       ID    #REQUIRED
    teacher    IDREF #REQUIRED
    nrStudents CDATA #IMPLIED >
  <!ELEMENT Class EMPTY >
   <!ATTLIST Class
     day    CDATA #REQUIRED
     hour   CDATA #REQUIRED >

]>
<Hogwarts>
 <Rooms>
  <Room name="TheDungeon" nrSeats="34"/>
  <Room name="TheCabin" nrSeats="163"/>
  <Room name="HC4" nrSeats="200"/>
 </Rooms>
 <Teachers>
  <Teacher name="Snape" room="TheDungeon">
   <Title>Professor</Title>
  </Teacher>
  <Teacher name="Hagrid" room="TheCabin"/>
  <Teacher name="Broberg" room="HC4"/>
 </Teachers>
 <Courses>
  <Course name="Potioncraft" teacher="Snape" nrStudents="28">
   <Class day="Monday" hour="10"/>
   <Class day="Monday" hour="12"/>
  </Course>
  <Course name="Handling_of_Wild_Creatures" teacher="Hagrid">
   <Class day="Saturday" hour="13"/>
   <Class day="Thursday" hour="7"/>
  </Course>
  <Course name="Databases" teacher="Broberg" nrStudents="300">
   <Class day="Monday" hour="13"/>
   <Class day="Wednesday" hour="13"/>
  </Course>
  <Course name="Advanced_Databases" teacher="Broberg" nrStudents="200"/>
 </Courses>
</Hogwarts>