<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hogwarts [

<!ELEMENT Hogwarts (Teachers, TeacherTitles, Rooms, Courses, Classes)>

<!ELEMENT Teachers (Teacher*) >
  <!ELEMENT Teacher EMPTY >
   <!ATTLIST Teacher
     name ID    #REQUIRED
     room IDREF #REQUIRED >

 
 <!ELEMENT TeacherTitles (TeacherTitle*)>
  <!ELEMENT TeacherTitle EMPTY >
   <!ATTLIST TeacherTitle
     teacher IDREF #REQUIRED
     title   CDATA #REQUIRED >
 
 <!ELEMENT Rooms (Room*)>
  <!ELEMENT Room EMPTY>
   <!ATTLIST Room
     name    ID    #REQUIRED
     nrSeats CDATA #IMPLIED >

 
 <!ELEMENT Courses (Course*)>
  <!ELEMENT Course EMPTY>
   <!ATTLIST Course
     name       ID    #REQUIRED
     teacher    IDREF #REQUIRED
     nrStudents CDATA #IMPLIED >
 
 <!ELEMENT Classes (Class*)>
  <!ELEMENT Class EMPTY>
   <!ATTLIST Class
     course IDREF #REQUIRED
     day    CDATA #REQUIRED
     hour   CDATA #REQUIRED >

]>
<Hogwarts>
 <Teachers>
   <Teacher name="Snape" room="The_Dungeon"/>
   <Teacher name="Hagrid" room="The_Cabin"/>
 </Teachers>
 <TeacherTitles>
  <TeacherTitle teacher="Snape" title="Professor"/>
 </TeacherTitles>
 <Rooms>
  <Room name="The_Dungeon" nrSeats="34"/>
  <Room name="The_Cabin" nrSeats="163"/>
 </Rooms>
 <Courses>
  <Course name="Potioncraft" teacher="Snape" nrStudents="28"/>
  <Course name="Handling_of_Wild_Creatures" teacher="Hagrid"/>
 </Courses>
 <Classes>
  <Class course="Potioncraft" day="Monday" hour="10"/>
  <Class course="Handling_of_Wild_Creatures" day="Saturday" hour="13"/>
  <Class course="Handling_of_Wild_Creatures" day="Thursday" hour="7"/>
 </Classes>
</Hogwarts>